### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by SoerenBusse** [erniejunior/UT390B_Arduino_Library#1]
Do you have a kind oft tutorial how to connect the UT390B to the Arduino?

**Comment by ernestum** [comment]
Have a look here ![here](https://cloud.githubusercontent.com/assets/1250234/9353794/7f0c89c0-466b-11e5-8c4e-055b574846e9.jpg)(taken from http://blog.qartis.com/arduino-laser-distance-meter/)
But be careful with the voltages. The thing wants 2.7V! I will write something to the README on how to deal with that ...
![scan 1](https://cloud.githubusercontent.com/assets/1250234/9354402/5a5db5d6-4670-11e5-9d61-9cdacc2f461e.jpeg)

**Comment by ernestum** [comment]
Have a look at the new version of the readme and let me know if what I wrote is understandable. I close this issue for now.
